POST http://127.0.0.1:8000/authentication/login
Content-Type: application/json

{"username": "alamorre", "password": "Pass1234!"}

###

POST http://127.0.0.1:8000/authentication/signup
Content-Type: application/json

{"username": "alamorre", "password": "Pass1234!", "email": "zack@gmail.com"}

###

GET http://127.0.0.1:8000/authentication/test_token
Content-Type: application/json

{}