POST http://127.0.0.1:8000/authentication/login
Content-Type: application/json

{"email": "sean@gmail.com", "password": "Pass1234!"}

###

POST http://127.0.0.1:8000/authentication/logout
Content-Type: application/json
Authorization: Token 28354a4f171cdbc8fdcd478981ed33e3c38f83f5

###

POST http://127.0.0.1:8000/authentication/signup
Content-Type: application/json

{"email": "sean@gmail.com", "password": "Pass1234!"}

###

GET http://127.0.0.1:8000/authentication/test_token
Content-Type: application/json
Authorization: Token 7af7a54028d922c35e8f1ada3e771cdbe85802d3

{}